name: Build approach_09_optimize_performance / subapproach_03_webgl_optimization / method_02_texture_cache_blocking

on:
  push:
    paths:
      - 'src/approach_09_optimize_performance/subapproach_03_webgl_optimization/method_02_texture_cache_blocking/**'

# GitHub Pages へのデプロイに必要な権限を設定
permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      directory: ./src/approach_09_optimize_performance/subapproach_03_webgl_optimization/method_02_texture_cache_blocking
