name: Build approach_01_baseline

on:
  push:
    paths:
      - 'src/approach_01_baseline/**'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      directory: ./src/approach_01_baseline
