name: Build approach_01_baseline

on:
  push:
    paths:
      - 'src/approach_01_baseline/**'

# GitHub Pages へのデプロイに必要な権限を設定
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      directory: ./src/approach_01_baseline
