name: Build approach_05_object_pose_hybrid

on:
  push:
    paths:
      - 'src/approach_05_object_pose_hybrid/**'

# GitHub Pages へのデプロイに必要な権限を設定
permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      directory: ./src/approach_05_object_pose_hybrid
