name: Build approach_06_min_size_enforcer

on:
  push:
    paths:
      - 'src/approach_06_min_size_enforcer/**'

# GitHub Pages へのデプロイに必要な権限を設定
permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      directory: ./src/approach_06_min_size_enforcer
