name: Build approach_02_roi

on:
  push:
    paths:
      - 'src/approach_02_roi/**'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      directory: ./src/approach_02_roi
